# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# vim: set nospell:
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
